name: CI/CD GitOps

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build image
      # REPLACE YOUR_DOCKERHUB_USER
      run: docker build -t YOUR_DOCKERHUB_USER/myapp:${{ github.sha }} .

    - name: Login DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push image
      # REPLACE YOUR_DOCKERHUB_USER
      run: docker push YOUR_DOCKERHUB_USER/myapp:${{ github.sha }}

    - name: Update manifest
      # REPLACE YOUR_DOCKERHUB_USER
      run: |
        sed -i "s|image: .*|image: YOUR_DOCKERHUB_USER/myapp:${{ github.sha }}|" k8s/deployment.yaml
        git config user.name github-actions
        git config user.email actions@github.com
        git add k8s/deployment.yaml
        git commit -m "update image tag to ${{ github.sha }}"
        git push
